version: '2'

services:
   db:
     image: postgres:9.6.2
     volumes:
       - db_data:/var/lib/postgres
     restart: always
     environment:
       POSTGRES_USER: memory
       POSTGRES_PASSWORD: hole
       POSTGRES_DB: memoryhole

   db-devops:
     depends_on:
       - db
     image: hughjfchen/db-devops:latest
     ports:
       - "8000:3000"
     restart: always
     environment:
       DATABASE_URL: jdbc:postgresql://db/memoryhole?user=memory&password=hole
volumes:
    db_data:
