(ns db-devops.db.checklist
  (:require [db-devops.db.core :as db]
            [schema.core :as s]))

;; verify functions for checklist
;; all functions should be pure. and accept two or more parameters
;; the first parameter is the source result, the second is the target
;; result(if any), and the rest is the extra parameters defined in this
;; checklist :rule-fn-extra-paras


;; some pre-defined functions

(defn verify-fn-eq[s t & rest]
  (let [source-result (get-in s [:execute :output :result :source])]
    (some #(= source-result %) rest)))

(defn verify-fn-gt[s t & rest]
  (let [source-result (biginteger (get-in s [:execute :output :result :source]))]
    (some #(> source-result %) rest)))

(defn verify-fn-lt[s t & rest]
  (let [source-result (biginteger (get-in s [:execute :output :result :source]))]
    (some #(< source-result %) rest)))

(defn verify-fn-ge[s t & rest]
  (let [source-result (biginteger (get-in s [:execute :output :result :source]))]
    (some #(>= source-result %) rest)))

(defn verify-fn-le[s t & rest]
  (let [source-result (biginteger (get-in s [:execute :output :result :source]))]
    (some #(<= source-result %) rest)))

(defn verify-fn-tf[s t & rest]
  (let [source-result (get-in s [:execute :output :result :source])]
    (boolean source-result)))

(defn verify-fn-compare[s t & rest]
  (let [source-result (get-in s [:execute :output :result :source])
        target-result (get-in s [:execute :output :result :target])]
    (= source-result target-result)))

(def ALL-CHECKLIST [{:checklist-id 1 :first-cat :aix-check :second-cat :system-config :title "系统版本" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras ["7100-03-05"] :rule-fn verify-fn-eq :rule-description "oslevel=7100-03-05 or 6100-09-05"}}
                    {:checklist-id 2 :first-cat :aix-check :second-cat :system-config :title "系统内存" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :memsize]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "目标memsize>=源memsize"}}
                    {:checklist-id 3 :first-cat :aix-check :second-cat :system-config :title "系统cpu" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :numproc]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "目标numproc>=源numproc"}}
                    {:checklist-id 4 :first-cat :aix-check :second-cat :system-config :title "主机时间" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :nowtime]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "nowtime=beijingtime"}}
                    {:checklist-id 5 :first-cat :aix-check :second-cat :system-config :title "系统时区" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :timezone]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "timezone=BEIST-8 or ASIA/Shanghai"}}
                    {:checklist-id 6 :first-cat :aix-check :second-cat :system-config :title "xLC版本" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :clevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "clevel>=13.1.2.0"}}
                    {:checklist-id 7 :first-cat :aix-check :second-cat :system-config :title "换页空间" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :pgspace]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "pagespace=memsize*1.5 or >=8G"}}
                    {:checklist-id 8 :first-cat :aix-check :second-cat :system-config :title "端口配置" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:db2portinfo]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "db2c_<instname> = 源db2c_<instname>"}}
                    {:checklist-id 9 :first-cat :aix-check :second-cat :system-config :title "java JDK版本" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path []}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "jdk_version>=源jdk_version"}}
                    {:checklist-id 10 :first-cat :aix-check :second-cat :system-config :title "/etc/hosts文件" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:hostsinfo]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "/etc/hosts文件=源/etc/hosts文件"}}

                    ; [:aix-check :software-deployment]
                    {:checklist-id 11 :first-cat :aix-check :second-cat :software-deployment :title "opsware部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:opsware]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器部署OPSware SA agent"}}
                    {:checklist-id 12 :first-cat :aix-check :second-cat :software-deployment :title "itm部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:itm]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器部署ITM agent"}}
                    {:checklist-id 13 :first-cat :aix-check :second-cat :software-deployment :title "nim部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:nim]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器加入NIMServer"}}
                    {:checklist-id 14 :first-cat :aix-check :second-cat :software-deployment :title "nbu部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:nbu]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器完成nbu client部署"}}
                    {:checklist-id 15 :first-cat :aix-check :second-cat :software-deployment :title "DB2监控脚本部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:db2_mon]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器完成DB2监控部署"}}
                    {:checklist-id 16 :first-cat :aix-check :second-cat :software-deployment :title "数据库tivoli监控部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:tivoli]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器完成数据库tivoli监控部署"}}
                    {:checklist-id 17 :first-cat :aix-check :second-cat :software-deployment :title "看板监控部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:kanban]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器完成看板监控部署"}}
                    {:checklist-id 18 :first-cat :aix-check :second-cat :software-deployment :title "db2产品部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path []}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "针对不同的db2版本升级，需要检查不同的db2产品"}}
                    {:checklist-id 19 :first-cat :aix-check :second-cat :software-deployment :title "CDC运行状态监控部署" :execute {:script-name "check_aix_proc.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:cdc_run]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "对于数据库迁移，要求新服务器完成cdc运行状态监控部署"}}

                                        ; [:aix-check :system-parameter]
                    {:checklist-id 19 :first-cat :aix-check :second-cat :system-parameter :title "maxuproc" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:sysinfo :maxproc]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "该值为要求的最小值。如果已设置为较高的值，则不需要更改。"}}
                    {:checklist-id 20 :first-cat :aix-check :second-cat :system-parameter :title "sb_max" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :sb_max]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "sb_max>=1310720"}}
                    {:checklist-id 21 :first-cat :aix-check :second-cat :system-parameter :title "rfc1323" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :rfc1323]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "rfc1323>=1"}}
                    {:checklist-id 22 :first-cat :aix-check :second-cat :system-parameter :title "tcp_sendspace" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_sendspace]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_sendspace>=1048576"}}
                    {:checklist-id 23 :first-cat :aix-check :second-cat :system-parameter :title "tcp_recvspace" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_recvspace]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_recvspace>=1048576"}}
                    {:checklist-id 24 :first-cat :aix-check :second-cat :system-parameter :title "udp_sendspace" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :udp_sendspace]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "udp_sendspace>=262144"}}
                    {:checklist-id 25 :first-cat :aix-check :second-cat :system-parameter :title "udp_recvspace" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :udp_recvspace]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "udp_recvspace>=262144"}}
                    {:checklist-id 26 :first-cat :aix-check :second-cat :system-parameter :title "ipqmaxlen" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :ipqmaxlen]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ipqmaxlen>=250"}}
                    {:checklist-id 27 :first-cat :aix-check :second-cat :system-parameter :title "somaxconn" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :somaxconn]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "somaxconn>=1024"}}
                    {:checklist-id 28 :first-cat :aix-check :second-cat :system-parameter :title "tcp_keepidle" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_keepidle]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_keepidle=300"}}
                    {:checklist-id 29 :first-cat :aix-check :second-cat :system-parameter :title "tcp_keepcnt" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_keepcnt]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_keepcnt=5"}}
                    {:checklist-id 30 :first-cat :aix-check :second-cat :system-parameter :title "tcp_keepintvl" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_keepintvl]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_keepintvl=12"}}
                    {:checklist-id 31 :first-cat :aix-check :second-cat :system-parameter :title "tcp_keepinit" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_keepinit]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_keepinit=120"}}
                    {:checklist-id 32 :first-cat :aix-check :second-cat :system-parameter :title "clean_partial_conns" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :clean_partial_conns]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "clean_partial_conns=1"}}
                    {:checklist-id 33 :first-cat :aix-check :second-cat :system-parameter :title "ip6srcrouteforward" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :ip6srcrouteforward]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ip6srcrouteforward=0"}}
                    {:checklist-id 34 :first-cat :aix-check :second-cat :system-parameter :title "ipignoreredirects" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :ipignoreredirects]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ipignoreredirects=1"}}
                    {:checklist-id 35 :first-cat :aix-check :second-cat :system-parameter :title "ipsendredirects" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :ipsendredirects]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ipsendredirects=0"}}
                    {:checklist-id 36 :first-cat :aix-check :second-cat :system-parameter :title "ipsrcrouterecv" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :ipsrcrouterecv]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ipsrcrouterecv=1"}}
                    {:checklist-id 37 :first-cat :aix-check :second-cat :system-parameter :title "tcp_nagle_limit" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_nagle_limit]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_nagle_limit=1"}}
                    {:checklist-id 38 :first-cat :aix-check :second-cat :system-parameter :title "tcp_nodelayack" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_nodelayack]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_nodelayack=1"}}
                    {:checklist-id 39 :first-cat :aix-check :second-cat :system-parameter :title "tcp_tcpsecure" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:noinfo :tcp_tcpsecure]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "tcp_tcpsecure=5"}}
                    {:checklist-id 40 :first-cat :aix-check :second-cat :system-parameter :title "minfree" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :minfree]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "if memsize < 8GB,then minfree=4096
if memsize > 8GB,then minfree=8192"}}
                    {:checklist-id 41 :first-cat :aix-check :second-cat :system-parameter :title "maxfree" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :maxfree]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "minfree + 512"}}
                    {:checklist-id 42 :first-cat :aix-check :second-cat :system-parameter :title "minperm%" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :minperm%]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "(minperm%<=5) && (maxperm%<=10) && (maxperm%- minperm%>=2) && (maxclient%<=maxperm%)"}}
                    {:checklist-id 43 :first-cat :aix-check :second-cat :system-parameter :title "maxperm%" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :maxperm%]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "(minperm%<=5) && (maxperm%<=10) && (maxperm%- minperm%>=2) && (maxclient%<=maxperm%)"}}
                    {:checklist-id 44 :first-cat :aix-check :second-cat :system-parameter :title "maxclient%" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :maxclient%]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "(minperm%<=5) && (maxperm%<=10) && (maxperm%- minperm%>=2) && (maxclient%<=maxperm%)"}}
                    {:checklist-id 45 :first-cat :aix-check :second-cat :system-parameter :title "strict_maxclient" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :strict_maxclient]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "strict_maxclient=1"}}
                    {:checklist-id 46 :first-cat :aix-check :second-cat :system-parameter :title "strict_maxperm" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :strict_maxperm]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "strict_maxperm=1"}}
                    {:checklist-id 47 :first-cat :aix-check :second-cat :system-parameter :title "lru_file_repage" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :lru_file_repage]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "lru_file_repage=0"}}
                    {:checklist-id 48 :first-cat :aix-check :second-cat :system-parameter :title "v_pinshm" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vmoinfo :v_pinshm]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "v_pinshm=1"}}
                    {:checklist-id 49 :first-cat :aix-check :second-cat :system-parameter :title "j2_maxPageReadAhead" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :j2_maxPageReadAhead]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "j2_maxPageReadAhead=128"}}
                    {:checklist-id 50 :first-cat :aix-check :second-cat :system-parameter :title "j2_maxRandomWrite" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :j2_maxRandomWrite]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "j2_maxRandomWrite=0"}}
                    {:checklist-id 51 :first-cat :aix-check :second-cat :system-parameter :title "j2_minPageReadAhead" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :j2_minPageReadAhead]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "j2_minPageReadAhead=2"}}
                    {:checklist-id 52 :first-cat :aix-check :second-cat :system-parameter :title "maxpgahead" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :maxpgahead]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "maxpgahead=8"}}
                    {:checklist-id 53 :first-cat :aix-check :second-cat :system-parameter :title "minpgahead" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :minpgahead]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "minpgahead=2"}}
                    {:checklist-id 54 :first-cat :aix-check :second-cat :system-parameter :title "maxrandwrt" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :maxrandwrt]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "maxrandwrt=0"}}
                    {:checklist-id 55 :first-cat :aix-check :second-cat :system-parameter :title "j2_nBufferPerPagerDevice" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :j2_nBufferPerPagerDevice]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "j2_nBufferPerPagerDevice=512"}}
                    {:checklist-id 56 :first-cat :aix-check :second-cat :system-parameter :title "numfsbufs" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :numfsbufs]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "numfsbufs=196"}}
                    {:checklist-id 57 :first-cat :aix-check :second-cat :system-parameter :title "j2_nPagesPerWriteBehindCluster" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :j2_nPagesPerWriteBehindCluster]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "j2_nPagesPerWriteBehindCluster=32"}}
                    {:checklist-id 58 :first-cat :aix-check :second-cat :system-parameter :title "pv_min_pbuf" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :pv_min_pbuf]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "pv_min_pbuf=512"}}
                    {:checklist-id 59 :first-cat :aix-check :second-cat :system-parameter :title "sync_release_ilock" :execute {:script-name "get_aix_sysparm.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:iooinfo :sync_release_ilock]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "sync_release_ilock=0"}}

                    ; [:user-check :user-config]
                    {:checklist-id 60 :first-cat :user-check :second-cat :user-config :title "用户目录" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:home]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "用户目录路径=源用户目录路径"}}
                    {:checklist-id 61 :first-cat :user-check :second-cat :user-config :title "用户名" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:uname]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "username=源username"}}
                    {:checklist-id 62 :first-cat :user-check :second-cat :user-config :title "用户id" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:id]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "userid=源userid"}}
                    {:checklist-id 63 :first-cat :user-check :second-cat :user-config :title "组名" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:pgrp]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "groupname=源grouname"}}
                    {:checklist-id 64 :first-cat :user-check :second-cat :user-config :title "组id" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:groups]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "groupid=源groupid"}}
                    {:checklist-id 65 :first-cat :user-check :second-cat :user-config :title "密码有效期" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:expires]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "expired=源expired"}}
                    {:checklist-id 66 :first-cat :user-check :second-cat :user-config :title "fsize" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:fsize]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fsize=-1"}}
                    {:checklist-id 67 :first-cat :user-check :second-cat :user-config :title "cpu  " :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:cpu]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "cpu=-1"}}
                    {:checklist-id 68 :first-cat :user-check :second-cat :user-config :title "data" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:data]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "data=-1"}}
                    {:checklist-id 69 :first-cat :user-check :second-cat :user-config :title "stack" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:stack]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "stack=-1"}}
                    {:checklist-id 70 :first-cat :user-check :second-cat :user-config :title "rss" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:rss]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "rss=-1"}}
                    {:checklist-id 71 :first-cat :user-check :second-cat :user-config :title "nofiles" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:nofiles]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "nofiles=-1"}}
                    {:checklist-id 72 :first-cat :user-check :second-cat :user-config :title "fsize_hard" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:fsize_hard]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fsize_hard=-1"}}
                    {:checklist-id 73 :first-cat :user-check :second-cat :user-config :title "cpu_hard" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:cpu_hard]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "cpu_hard=-1"}}
                    {:checklist-id 74 :first-cat :user-check :second-cat :user-config :title "data_hard" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:data_hard]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "data_hard=-1"}}
                    {:checklist-id 75 :first-cat :user-check :second-cat :user-config :title "stack_hard" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:stack_hard]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "stack_hard=-1"}}
                    {:checklist-id 76 :first-cat :user-check :second-cat :user-config :title "rss_hard" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:rss_hard]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "rss_hard=-1"}}
                    {:checklist-id 77 :first-cat :user-check :second-cat :user-config :title "nofiles_hard" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:nofiles_hard]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "nofiles_hard=-1"}}
                    {:checklist-id 78 :first-cat :user-check :second-cat :user-config :title "capabilities" :execute {:script-name "get_aix_usercfg.py" :input [{:name :machine :command-line "-o"} {:name :username :command-line "-u"}] :output {:field-path [:capabilities]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "capabilities=CAP_BYPASS_RAC_VMM,CAP_PROPAGATE"}}

                    ; [:storage-check :storage-config]
                    {:checklist-id 79 :first-cat :storage-check :second-cat :storage-config :title "rootvg镜像" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:rootvgmir]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "rootvgmir是否"}}
                    {:checklist-id 80 :first-cat :storage-check :second-cat :storage-config :title "vg容量检查" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:totalsize]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "vgsize>=源vgsize"}}
                    {:checklist-id 81 :first-cat :storage-check :second-cat :storage-config :title "vg状态检查" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:vgstat]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "vgstate=active"}}
                    {:checklist-id 82 :first-cat :storage-check :second-cat :storage-config :title "IOPS值" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "IOPS>=源IOPS"}}
                    {:checklist-id 83 :first-cat :storage-check :second-cat :storage-config :title "throughput值" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "thoughput>=源throughput"}}
                    {:checklist-id 84 :first-cat :storage-check :second-cat :filesystem :title "实例目录文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "insthomesize>=源insthomesize"}}
                    {:checklist-id 85 :first-cat :storage-check :second-cat :filesystem :title "数据库诊断日志文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbdiagsize>=源dbdiagsize"}}
                    {:checklist-id 86 :first-cat :storage-check :second-cat :filesystem :title "管理文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "managesize>=源managesize"}}
                    {:checklist-id 87 :first-cat :storage-check :second-cat :filesystem :title "数据库文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbdatasize>=源dbdatasize"}}
                    {:checklist-id 88 :first-cat :storage-check :second-cat :filesystem :title "数据库日志文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbactlogsize>=源dbactlogsize"}}
                    {:checklist-id 89 :first-cat :storage-check :second-cat :filesystem :title "数据库日志镜像文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbmirlogsize>=源dbmirlogsize"}}
                    {:checklist-id 90 :first-cat :storage-check :second-cat :filesystem :title "归档日志文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbarchm1size>=源dbarchm1size"}}
                    {:checklist-id 91 :first-cat :storage-check :second-cat :filesystem :title "第二归档日志文件系统大小" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbarchm2size>=源dbarchm2size"}}
                    {:checklist-id 92 :first-cat :storage-check :second-cat :filesystem :title "DB2实例目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "insthomepath=源insthomepath"}}
                    {:checklist-id 93 :first-cat :storage-check :second-cat :filesystem :title "管理目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "managepath=源managepath"}}
                    {:checklist-id 94 :first-cat :storage-check :second-cat :filesystem :title "数据库诊断日志目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbdiagpath=源dbdiagpath"}}
                    {:checklist-id 95 :first-cat :storage-check :second-cat :filesystem :title "活动日志数据目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbactlogpath=源dbactlogpath"}}
                    {:checklist-id 96 :first-cat :storage-check :second-cat :filesystem :title "镜像日志目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbmirlogpath=源dbmirlogpath"}}
                    {:checklist-id 97 :first-cat :storage-check :second-cat :filesystem :title "数据库文件系统目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbdatapath=源dbdatapath"}}
                    {:checklist-id 98 :first-cat :storage-check :second-cat :filesystem :title "归档日志目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbarchm1path=源dbarchm1path"}}
                    {:checklist-id 99 :first-cat :storage-check :second-cat :filesystem :title "第二归档日志目录" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "dbarchm2path=源dbarchm2path"}}
                    {:checklist-id 100 :first-cat :storage-check :second-cat :filesystem :title "实例目录文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs2"}}
                    {:checklist-id 101 :first-cat :storage-check :second-cat :filesystem :title "数据库诊断日志文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs2"}}
                    {:checklist-id 102 :first-cat :storage-check :second-cat :filesystem :title "管理文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs3"}}
                    {:checklist-id 103 :first-cat :storage-check :second-cat :filesystem :title "数据库文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs4"}}
                    {:checklist-id 104 :first-cat :storage-check :second-cat :filesystem :title "数据库日志文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs5"}}
                    {:checklist-id 105 :first-cat :storage-check :second-cat :filesystem :title "数据库日志镜像文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs6"}}
                    {:checklist-id 106 :first-cat :storage-check :second-cat :filesystem :title "归档日志文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs7"}}
                    {:checklist-id 107 :first-cat :storage-check :second-cat :filesystem :title "第二归档日志文件系统类型" :execute {:script-name "get_aix_storage.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "fstype=jfs8"}}

                    ; [:db-check :db-backup]
                    {:checklist-id 108 :first-cat :db-check :second-cat :db-backup :title "源系统数据库是否做备份" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 109 :first-cat :db-check :second-cat :db-backup :title "源系统数据库是否做表级备份" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 110 :first-cat :db-check :second-cat :db-backup :title "备份db2set环境参数" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 111 :first-cat :db-check :second-cat :db-backup :title "备份db cfg数据库参数" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 112 :first-cat :db-check :second-cat :db-backup :title "备份dbm cfg实例参数" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 113 :first-cat :db-check :second-cat :db-backup :title "备份程序包packages" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 114 :first-cat :db-check :second-cat :db-backup :title "外部函数及权限，备份~/sqllib/functions下程序" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 115 :first-cat :db-check :second-cat :db-backup :title "检查外部函数是否用fence用户执行" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 116 :first-cat :db-check :second-cat :db-backup :title "备份db2nodes.cfg" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}

                    ; [:db-check :db-status]
                    {:checklist-id 117 :first-cat :db-check :second-cat :db-status :title "实例是否启动" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 118 :first-cat :db-check :second-cat :db-status :title "数据库是否可连接" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 119 :first-cat :db-check :second-cat :db-status :title "表空间状态是否正常" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 120 :first-cat :db-check :second-cat :db-status :title "表空间、表大小是否达到限值" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 121 :first-cat :db-check :second-cat :db-status :title "表空间类型是否发生变化" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 122 :first-cat :db-check :second-cat :db-status :title "HADR状态" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 123 :first-cat :db-check :second-cat :db-status :title "检查DB2编目信息" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "db2_catalog_info=源db2_catalog_info"}}
                    {:checklist-id 124 :first-cat :db-check :second-cat :db-status :title "DB2产品的license信息" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}
                    {:checklist-id 125 :first-cat :db-check :second-cat :db-status :title "联邦信息" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "是否"}}

                    ; [:db-check :db-privilege]
                    {:checklist-id 126 :first-cat :db-check :second-cat :db-privilege :title "用户权限" :execute {:script-name "get-aix-osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description ""}}

                    ; [:db-check :environment]
                    {:checklist-id 127 :first-cat :db-check :second-cat :environment :title "DB2_LOAD_COPY_NO_OVERRIDE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "NONRECOVERABLE"}}
                    {:checklist-id 128 :first-cat :db-check :second-cat :environment :title "DB2_MAX_GLOBAL_SNAPSHOT_SIZE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "20971520"}}
                    {:checklist-id 129 :first-cat :db-check :second-cat :environment :title "DB2_USE_ALTERNATE_PAGE_CLEANING" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 130 :first-cat :db-check :second-cat :environment :title "DB2_LOGGER_NON_BUFFERED_IO" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 131 :first-cat :db-check :second-cat :environment :title "DB2_SNAPSHOT_NOAUTH" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "YES"}}
                    {:checklist-id 132 :first-cat :db-check :second-cat :environment :title "DB2_TRUST_MDC_BLOCK_FULL_HINT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "YES"}}
                    {:checklist-id 133 :first-cat :db-check :second-cat :environment :title "DB2_MDC_ROLLOUT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "DEFER"}}
                    {:checklist-id 134 :first-cat :db-check :second-cat :environment :title "DB2_EVALUNCOMMITTED" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 135 :first-cat :db-check :second-cat :environment :title "DB2_SKIPINSERTED" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 136 :first-cat :db-check :second-cat :environment :title "DB2SOSNDBUF" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1048576"}}
                    {:checklist-id 137 :first-cat :db-check :second-cat :environment :title "DB2SORCVBUF" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1048576"}}
                    {:checklist-id 138 :first-cat :db-check :second-cat :environment :title "DB2_ANTIJOIN" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "YES"}}
                    {:checklist-id 139 :first-cat :db-check :second-cat :environment :title "DB2_FORCE_FCM_BP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 140 :first-cat :db-check :second-cat :environment :title "DB2_PARALLEL_IO" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "*"}}
                    {:checklist-id 141 :first-cat :db-check :second-cat :environment :title "DB2COMM" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "TCPIP"}}
                    {:checklist-id 142 :first-cat :db-check :second-cat :environment :title "DB2AUTOSTART" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "YES"}}
                    {:checklist-id 143 :first-cat :db-check :second-cat :environment :title "DB2CODEPAGE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1386"}}

                    ; [:db-check :instance-config]
                    {:checklist-id 144 :first-cat :db-check :second-cat :instance-config :title "FEDERATED" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "NO"}}
                    {:checklist-id 145 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_BUFPOOL" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 146 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_LOCK" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 147 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_SORT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 148 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_STMT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 149 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_TABLE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 150 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_TIMESTAMP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 151 :first-cat :db-check :second-cat :instance-config :title "DFT_MON_UOW" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 152 :first-cat :db-check :second-cat :instance-config :title "HEALTH_MON" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 153 :first-cat :db-check :second-cat :instance-config :title "MON_HEAP_SZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1024（1024<=$<=10240）"}}
                    {:checklist-id 154 :first-cat :db-check :second-cat :instance-config :title "AUDIT_BUF_SZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1024"}}
                    {:checklist-id 155 :first-cat :db-check :second-cat :instance-config :title "INSTANCE_MEMORY" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "主机总内存*0.55/4K（2G<=$<=主机总内存*0.55/4K，在同一主机运行多实例的情况下必须满足所有实例的instance_memory*4K之和小于等于主机总内存*0.55）     >=2048 and $ <= 0.55*# TOTAL_MEMORY"}}
                    {:checklist-id 156 :first-cat :db-check :second-cat :instance-config :title "SHEAPTHRES" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "0"}}
                    {:checklist-id 157 :first-cat :db-check :second-cat :instance-config :title "KEEPFENCED" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "NO"}}
                    {:checklist-id 158 :first-cat :db-check :second-cat :instance-config :title "FENCED_POOL" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "0"}}
                    {:checklist-id 159 :first-cat :db-check :second-cat :instance-config :title "NUM_INITFENCED" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "0"}}
                    {:checklist-id 160 :first-cat :db-check :second-cat :instance-config :title "INDEXREC" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "RESTART"}}
                    {:checklist-id 161 :first-cat :db-check :second-cat :instance-config :title "SVCENAME" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "要求设置为services名称（建议名称DB2c<instname>），不能设置为具体端口值"}}
                    {:checklist-id 162 :first-cat :db-check :second-cat :instance-config :title "INTRA_PARALLEL" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "NO"}}

                    ; [:db-check :db-parameter]
                    {:checklist-id 163 :first-cat :db-check :second-cat :db-parameter :title "DFT_DEGREE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1"}}
                    {:checklist-id 164 :first-cat :db-check :second-cat :db-parameter :title "SELF_TUNING_MEM" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 165 :first-cat :db-check :second-cat :db-parameter :title "DATABASE_MEMORY" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "AUTOMATIC "}}
                    {:checklist-id 166 :first-cat :db-check :second-cat :db-parameter :title "DB_MEM_THRESH" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "10"}}
                    {:checklist-id 167 :first-cat :db-check :second-cat :db-parameter :title "LOCKLIST" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "10240"}}
                    {:checklist-id 168 :first-cat :db-check :second-cat :db-parameter :title "MAXLOCKS" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "20"}}
                    {:checklist-id 169 :first-cat :db-check :second-cat :db-parameter :title "PCKCACHESZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "4096"}}
                    {:checklist-id 170 :first-cat :db-check :second-cat :db-parameter :title "SHEAPTHRES_SHR" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "20480"}}
                    {:checklist-id 171 :first-cat :db-check :second-cat :db-parameter :title "SORTHEAP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "2048"}}
                    {:checklist-id 172 :first-cat :db-check :second-cat :db-parameter :title "DBHEAP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "AUTOMATIC"}}
                    {:checklist-id 173 :first-cat :db-check :second-cat :db-parameter :title "CATALOGCACHE_SZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "4096"}}
                    {:checklist-id 174 :first-cat :db-check :second-cat :db-parameter :title "LOGBUFSZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "4096"}}
                    {:checklist-id 175 :first-cat :db-check :second-cat :db-parameter :title "UTIL_HEAP_SZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "10240"}}
                    {:checklist-id 176 :first-cat :db-check :second-cat :db-parameter :title "STMTHEAP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "4096"}}
                    {:checklist-id 177 :first-cat :db-check :second-cat :db-parameter :title "APPLHEAPSZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "AUTOMATIC"}}
                    {:checklist-id 178 :first-cat :db-check :second-cat :db-parameter :title "APPL_MEMORY" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "AUTOMATIC"}}
                    {:checklist-id 179 :first-cat :db-check :second-cat :db-parameter :title "STAT_HEAP_SZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "AUTOMATIC"}}
                    {:checklist-id 180 :first-cat :db-check :second-cat :db-parameter :title "DLCHKTIME" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "10000"}}
                    {:checklist-id 181 :first-cat :db-check :second-cat :db-parameter :title "LOCKTIMEOUT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "10"}}
                    {:checklist-id 182 :first-cat :db-check :second-cat :db-parameter :title "TRACKMOD" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description " ON"}}
                    {:checklist-id 183 :first-cat :db-check :second-cat :db-parameter :title "MAXFILOP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "61440"}}
                    {:checklist-id 184 :first-cat :db-check :second-cat :db-parameter :title "LOGFILSIZ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "10240（512<=$<=102400）"}}
                    {:checklist-id 185 :first-cat :db-check :second-cat :db-parameter :title "LOGPRIMARY" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "按实际需要设置（$>=5）"}}
                    {:checklist-id 186 :first-cat :db-check :second-cat :db-parameter :title "LOGSECOND" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "0"}}
                    {:checklist-id 187 :first-cat :db-check :second-cat :db-parameter :title "ACTLOGPATH" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "/db/actlog/${InstName}/${DBName}"}}
                    {:checklist-id 188 :first-cat :db-check :second-cat :db-parameter :title "MIRRORLOGPATH" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "/db/mirlog/${InstName}/${DBName}"}}
                    {:checklist-id 189 :first-cat :db-check :second-cat :db-parameter :title "BLK_LOG_DSK_FUL" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "NO"}}
                    {:checklist-id 190 :first-cat :db-check :second-cat :db-parameter :title "BLOCKNONLOGGED" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "YES"}}
                    {:checklist-id 191 :first-cat :db-check :second-cat :db-parameter :title "MAX_LOG" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "30"}}
                    {:checklist-id 192 :first-cat :db-check :second-cat :db-parameter :title "NUM_LOG_SPAN" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "LOGPRIMARY*0.9"}}
                    {:checklist-id 193 :first-cat :db-check :second-cat :db-parameter :title "SOFTMAX" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "20M / (LOGFILSIZ*4K)*100
（10M / (LOGFILSIZ*4K)*100 <=$<= 50M / (LOGFILSIZ*4K)*100"}}
                    {:checklist-id 194 :first-cat :db-check :second-cat :db-parameter :title "LOGARCHMETH1" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "DISK:/db/archm1"}}
                    {:checklist-id 195 :first-cat :db-check :second-cat :db-parameter :title "LOGARCHMETH2" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "DISK:/db/archm2"}}
                    {:checklist-id 196 :first-cat :db-check :second-cat :db-parameter :title "AUTORESTART" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 197 :first-cat :db-check :second-cat :db-parameter :title "INDEXREC" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "SYSTEM|RESTART"}}
                    {:checklist-id 198 :first-cat :db-check :second-cat :db-parameter :title "LOGINDEXBUILD" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON"}}
                    {:checklist-id 199 :first-cat :db-check :second-cat :db-parameter :title "NUM_DB_BACKUPS" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "12"}}
                    {:checklist-id 200 :first-cat :db-check :second-cat :db-parameter :title "REC_HIS_RETENTN" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "12"}}
                    {:checklist-id 201 :first-cat :db-check :second-cat :db-parameter :title "AUTO_DEL_REC_OBJ" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 202 :first-cat :db-check :second-cat :db-parameter :title "AUTO_MAINT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 203 :first-cat :db-check :second-cat :db-parameter :title "AUTO_DB_BACKUP" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 204 :first-cat :db-check :second-cat :db-parameter :title "AUTO_TBL_MAINT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 205 :first-cat :db-check :second-cat :db-parameter :title "AUTO_RUNSTATS" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 206 :first-cat :db-check :second-cat :db-parameter :title "AUTO_STMT_STATS" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 207 :first-cat :db-check :second-cat :db-parameter :title "AUTO_STATS_PROF" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 208 :first-cat :db-check :second-cat :db-parameter :title "AUTO_PROF_UPD" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}
                    {:checklist-id 209 :first-cat :db-check :second-cat :db-parameter :title "AUTO_REORG" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "OFF"}}

                    ; [:db-check :hadr-config]
                    {:checklist-id 210 :first-cat :db-check :second-cat :hadr-config :title "DB2_HADR_SOSNDBUF" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1048576"}}
                    {:checklist-id 211 :first-cat :db-check :second-cat :hadr-config :title "DB2_HADR_SORCVBUF" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1048576"}}
                    {:checklist-id 212 :first-cat :db-check :second-cat :hadr-config :title "DB2_HADR_NO_IP_CHECK" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "NO【适用于容灾网络使用NAT转换的环境】"}}
                    {:checklist-id 213 :first-cat :db-check :second-cat :hadr-config :title "DB2_HADR_BUF_SIZE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "Max(Min(LOGBUFSZ)*4，4096)<=$<=( Max(LOGBUFSZ)*4)   >=4096 and <=10240"}}
                    {:checklist-id 214 :first-cat :db-check :second-cat :hadr-config :title "DB2_HADR_PEER_WAIT_LIMIT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "1"}}
                    {:checklist-id 215 :first-cat :db-check :second-cat :hadr-config :title "DB2_HADR_ROS" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ON （HADR备端只读，按需打开）"}}
                    {:checklist-id 216 :first-cat :db-check :second-cat :hadr-config :title "DB2_STANDBY_ISO" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "UR （ROS=ON时的建议值）"}}
                    {:checklist-id 217 :first-cat :db-check :second-cat :hadr-config :title "HADR_DBROLE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description ""}}
                    {:checklist-id 218 :first-cat :db-check :second-cat :hadr-config :title "HADR_LOCAL_HOST" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "hadr1_<sys>【生产】
hadr2_<sys>【容灾"}}
                    {:checklist-id 219 :first-cat :db-check :second-cat :hadr-config :title "HADR_LOCAL_SVC" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "hadr1_<instname>_<DBNAME>【生产】
hadr2_<instname>_<DBNAME>【容灾】"}}
                    {:checklist-id 220 :first-cat :db-check :second-cat :hadr-config :title "HADR_REMOTE_HOST" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "hadr2_{sys}【生产端】
hadr1_{sys}【容灾端】"}}
                    {:checklist-id 221 :first-cat :db-check :second-cat :hadr-config :title "HADR_REMOTE_SVC" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "hadr2_<instname>_<DBNAME>【生产端】
hadr1_<instname>_<DBNAME>【容灾端】"}}
                    {:checklist-id 222 :first-cat :db-check :second-cat :hadr-config :title "HADR_REMOTE_INST" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "<instname>"}}
                    {:checklist-id 223 :first-cat :db-check :second-cat :hadr-config :title "HADR_TIMEOUT" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "120（30<=$<=120）"}}
                    {:checklist-id 224 :first-cat :db-check :second-cat :hadr-config :title "HADR_SYNCMODE" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "ASYNC【远程容灾】
NEARSYNC【本地容灾】
SUPERASYNC【多点容灾】"}}
                    {:checklist-id 225 :first-cat :db-check :second-cat :hadr-config :title "HADR_PEER_WINDOW" :execute {:script-name "python get_aix_dbparm.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :port :command-line "-p"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn identity :rule-description "0"}}
                    ])
