(ns db-devops.db.verification
  (:require [schema.core :as s]
            [mount.core :refer [defstate]]))

(def ALL-VERIFICATION [
                                        ; [:db-check :db-status]
                       {:id 108 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "源系统数据库是否做备份" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 109 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "源系统数据库是否做表级备份" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 110 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "备份db2set环境参数" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 111 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "备份db cfg数据库参数" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 112 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "备份dbm cfg实例参数" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 113 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "备份程序包packages" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 114 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "外部函数及权限，备份~/sqllib/functions下程序" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 115 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "检查外部函数是否用fence用户执行" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}
                       {:id 116 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-status :second-cat-label "DB状态" :title "备份db2nodes.cfg" :execute {:script-name "get_aix_dbinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}

                    ; [:db-check :first-cat-label "DB检查" :db-status]
                       {:id 117 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-object :second-cat-label "DB对象" :title "实例是否启动" :execute {:script-name "get_aix_dbstat.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :db :command-line "-d"} {:name :version :command-line "-v"}] :output {:field-path [:instance_status]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description "是否"}}

                                        ; [:db-check :first-cat-label "DB检查" :db-privilege]
                    {:id 126 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-privilege :second-cat-label "DB权限" :title "用户权限" :execute {:script-name "get_aix_osinfo.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :port :command-line "-p"}] :output {:field-path [:osinfo :oslevel]}} :verify {:type :eq :rule-fn-extra-paras "7100-03-05" :rule-fn "verify-fn-eq" :rule-description ""}}

                    ; [:db-check :first-cat-label "DB检查" :environment]
                    {:id 127 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_LOAD_COPY_NO_OVERRIDE" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_LOAD_COPY_NO_OVERRIDE]}} :verify {:type :eq :rule-fn-extra-paras ["NONRECOVERABLE"] :rule-fn "verify-fn-eq" :rule-description "NONRECOVERABLE"}}
                    {:id 128 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_MAX_GLOBAL_SNAPSHOT_SIZE" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_MAX_GLOBAL_SNAPSHOT_SIZE]}} :verify {:type :eq :rule-fn-extra-paras [20971520] :rule-fn "verify-fn-eq" :rule-description "20971520"}}
                    {:id 129 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_USE_ALTERNATE_PAGE_CLEANING" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_USE_ALTERNATE_PAGE_CLEANING]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 130 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_LOGGER_NON_BUFFERED_IO" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_LOGGER_NON_BUFFERED_IO]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 131 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_SNAPSHOT_NOAUTH" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_SNAPSHOT_NOAUTH]}} :verify {:type :eq :rule-fn-extra-paras ["YES"] :rule-fn "verify-fn-eq" :rule-description "YES"}}
                    {:id 132 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_TRUST_MDC_BLOCK_FULL_HINT" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_TRUST_MDC_BLOCK_FULL_HINT]}} :verify {:type :eq :rule-fn-extra-paras ["YES"] :rule-fn "verify-fn-eq" :rule-description "YES"}}
                    {:id 133 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_MDC_ROLLOUT" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_MDC_ROLLOUT]}} :verify {:type :eq :rule-fn-extra-paras ["DEFER"] :rule-fn "verify-fn-eq" :rule-description "DEFER"}}
                    {:id 134 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_EVALUNCOMMITTED" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_EVALUNCOMMITTED]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 135 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_SKIPINSERTED" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_SKIPINSERTED]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 136 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2SOSNDBUF" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2SOSNDBUF]}} :verify {:type :eq :rule-fn-extra-paras [1048576] :rule-fn "verify-fn-eq" :rule-description "1048576"}}
                    {:id 137 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2SORCVBUF" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2SORCVBUF]}} :verify {:type :eq :rule-fn-extra-paras [1048576] :rule-fn "verify-fn-eq" :rule-description "1048576"}}
                    {:id 138 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_ANTIJOIN" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_ANTIJOIN]}} :verify {:type :eq :rule-fn-extra-paras ["YES"] :rule-fn "verify-fn-eq" :rule-description "YES"}}
                    {:id 139 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_FORCE_FCM_BP" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_FORCE_FCM_BP]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 140 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2_PARALLEL_IO" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_PARALLEL_IO]}} :verify {:type :eq :rule-fn-extra-paras ["*"] :rule-fn "verify-fn-eq" :rule-description "*"}}
                    {:id 141 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2COMM" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2COMM]}} :verify {:type :eq :rule-fn-extra-paras ["TCPIP"] :rule-fn "verify-fn-eq" :rule-description "TCPIP"}}
                    {:id 142 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2AUTOSTART" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2AUTOSTART]}} :verify {:type :eq :rule-fn-extra-paras ["YES"] :rule-fn "verify-fn-eq" :rule-description "YES"}}
                    {:id 143 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DB2CODEPAGE" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2CODEPAGE]}} :verify {:type :eq :rule-fn-extra-paras [1386] :rule-fn "verify-fn-eq" :rule-description "1386"}}

                    ; [:db-check :first-cat-label "DB检查" :instance-config]
                    {:id 144 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "FEDERATED" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:FEDERATED]}} :verify {:type :eq :rule-fn-extra-paras ["NO"] :rule-fn "verify-fn-eq" :rule-description "NO"}}
                    {:id 145 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_BUFPOOL" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_BUFPOOL]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 146 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_LOCK" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_LOCK]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 147 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_SORT" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_SORT]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 148 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_STMT" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_STMT]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 149 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_TABLE" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_TABLE]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 150 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_TIMESTAMP" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_TIMESTAMP]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 151 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "DFT_MON_UOW" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_MON_UOW]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 152 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "HEALTH_MON" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HEALTH_MON]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 153 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "MON_HEAP_SZ" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:MON_HEAP_SZ]}} :verify {:type :ge :rule-fn-extra-paras [1024] :rule-fn "verify-fn-ge" :rule-description "1024（1024<=$<=10240）"}}
                    {:id 154 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "AUDIT_BUF_SZ" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUDIT_BUF_SZ]}} :verify {:type :eq :rule-fn-extra-paras [1024] :rule-fn "verify-fn-eq" :rule-description "1024"}}
                    {:id 155 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "INSTANCE_MEMORY" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:INSTANCE_MEMORY]}} :verify {:type :ge :rule-fn-extra-paras [2000] :rule-fn "verify-fn-ge" :rule-description "主机总内存*0.55/4K（2G<=$<=主机总内存*0.55/4K，在同一主机运行多实例的情况下必须满足所有实例的instance_memory*4K之和小于等于主机总内存*0.55）     >=2048 and $ <= 0.55*# TOTAL_MEMORY"}}
                    {:id 156 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "SHEAPTHRES" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:SHEAPTHRES]}} :verify {:type :eq :rule-fn-extra-paras [0] :rule-fn "verify-fn-eq" :rule-description "0"}}
                    {:id 157 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "KEEPFENCED" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:KEEPFENCED]}} :verify {:type :eq :rule-fn-extra-paras ["NO"] :rule-fn "verify-fn-eq" :rule-description "NO"}}
                    {:id 158 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "FENCED_POOL" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:FENCED_POOL]}} :verify {:type :eq :rule-fn-extra-paras [0] :rule-fn "verify-fn-eq" :rule-description "0"}}
                    {:id 159 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "NUM_INITFENCED" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:NUM_INITFENCED]}} :verify {:type :eq :rule-fn-extra-paras [0] :rule-fn "verify-fn-eq" :rule-description "0"}}
                    {:id 160 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "INDEXREC" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:INDEXREC]}} :verify {:type :eq :rule-fn-extra-paras ["RESTART"] :rule-fn "verify-fn-eq" :rule-description "RESTART"}}
                    {:id 161 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "SVCENAME" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:SVCENAME]}} :verify {:type :eq :rule-fn-extra-paras ["DB2c"] :rule-fn "verify-fn-eq" :rule-description "要求设置为services名称（建议名称DB2c<instname>），不能设置为具体端口值"}}
                    {:id 162 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :instance-config :second-cat-label "实例配置" :title "INTRA_PARALLEL" :execute {:script-name "get_aix_dbmcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:INTRA_PARALLEL]}} :verify {:type :eq :rule-fn-extra-paras ["NO"] :rule-fn "verify-fn-eq" :rule-description "NO"}}

                    ; [:db-check :first-cat-label "DB检查" :db-parameter]
                    {:id 163 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "DFT_DEGREE" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DFT_DEGREE]}} :verify {:type :eq :rule-fn-extra-paras [1] :rule-fn "verify-fn-eq" :rule-description "1"}}
                    {:id 164 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "SELF_TUNING_MEM" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:SELF_TUNING_MEM]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 165 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "DATABASE_MEMORY" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DATABASE_MEMORY]}} :verify {:type :eq :rule-fn-extra-paras ["AUTOMATIC"] :rule-fn "verify-fn-eq" :rule-description "AUTOMATIC "}}
                    {:id 166 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "DB_MEM_THRESH" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB_MEM_THRESH]}} :verify {:type :eq :rule-fn-extra-paras [10] :rule-fn "verify-fn-eq" :rule-description "10"}}
                    {:id 167 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOCKLIST" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOCKLIST]}} :verify {:type :eq :rule-fn-extra-paras [10240] :rule-fn "verify-fn-eq" :rule-description "10240"}}
                    {:id 168 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "MAXLOCKS" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:MAXLOCKS]}} :verify {:type :eq :rule-fn-extra-paras [20] :rule-fn "verify-fn-eq" :rule-description "20"}}
                    {:id 169 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "PCKCACHESZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:PCKCACHESZ]}} :verify {:type :eq :rule-fn-extra-paras [4096] :rule-fn "verify-fn-eq" :rule-description "4096"}}
                    {:id 170 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "SHEAPTHRES_SHR" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:SHEAPTHRES_SHR]}} :verify {:type :eq :rule-fn-extra-paras [20480] :rule-fn "verify-fn-eq" :rule-description "20480"}}
                    {:id 171 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "SORTHEAP" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:SORTHEAP]}} :verify {:type :eq :rule-fn-extra-paras [2048] :rule-fn "verify-fn-eq" :rule-description "2048"}}
                    {:id 172 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "DBHEAP" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DBHEAP]}} :verify {:type :eq :rule-fn-extra-paras ["AUTOMATIC"] :rule-fn "verify-fn-eq" :rule-description "AUTOMATIC"}}
                    {:id 173 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "CATALOGCACHE_SZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:CATALOGCACHE_SZ]}} :verify {:type :eq :rule-fn-extra-paras [4096] :rule-fn "verify-fn-eq" :rule-description "4096"}}
                    {:id 174 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGBUFSZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGBUFSZ]}} :verify {:type :eq :rule-fn-extra-paras [4096] :rule-fn "verify-fn-eq" :rule-description "4096"}}
                    {:id 175 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "UTIL_HEAP_SZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:UTIL_HEAP_SZ]}} :verify {:type :eq :rule-fn-extra-paras [10240] :rule-fn "verify-fn-eq" :rule-description "10240"}}
                    {:id 176 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "STMTHEAP" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:STMTHEAP]}} :verify {:type :eq :rule-fn-extra-paras [4096] :rule-fn "verify-fn-eq" :rule-description "4096"}}
                    {:id 177 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "APPLHEAPSZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:APPLHEAPSZ]}} :verify {:type :eq :rule-fn-extra-paras ["AUTOMATIC"] :rule-fn "verify-fn-eq" :rule-description "AUTOMATIC"}}
                    {:id 178 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "APPL_MEMORY" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:APPL_MEMORY]}} :verify {:type :eq :rule-fn-extra-paras ["AUTOMATIC"] :rule-fn "verify-fn-eq" :rule-description "AUTOMATIC"}}
                    {:id 179 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "STAT_HEAP_SZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:STAT_HEAP_SZ]}} :verify {:type :eq :rule-fn-extra-paras ["AUTOMATIC"] :rule-fn "verify-fn-eq" :rule-description "AUTOMATIC"}}
                    {:id 180 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "DLCHKTIME" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DLCHKTIME]}} :verify {:type :eq :rule-fn-extra-paras [10000] :rule-fn "verify-fn-eq" :rule-description "10000"}}
                    {:id 181 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOCKTIMEOUT" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOCKTIMEOUT]}} :verify {:type :eq :rule-fn-extra-paras [10] :rule-fn "verify-fn-eq" :rule-description "10"}}
                    {:id 182 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "TRACKMOD" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:TRACKMOD]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description " ON"}}
                    {:id 183 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "MAXFILOP" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:MAXFILOP]}} :verify {:type :eq :rule-fn-extra-paras [61440] :rule-fn "verify-fn-eq" :rule-description "61440"}}
                    {:id 184 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGFILSIZ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGFILSIZ]}} :verify {:type :eq :rule-fn-extra-paras [10240] :rule-fn "verify-fn-eq" :rule-description "10240（512<=$<=102400）"}}
                    {:id 185 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGPRIMARY" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGPRIMARY]}} :verify {:type :ge :rule-fn-extra-paras [5] :rule-fn "verify-fn-ge" :rule-description "按实际需要设置（$>=5）"}}
                    {:id 186 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGSECOND" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGSECOND]}} :verify {:type :eq :rule-fn-extra-paras [0] :rule-fn "verify-fn-eq" :rule-description "0"}}
                    {:id 187 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "ACTLOGPATH" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:ACTLOGPATH]}} :verify {:type :eq :rule-fn-extra-paras ["/db/actlog/${InstName}/${DBName}"] :rule-fn "verify-fn-eq" :rule-description "/db/actlog/${InstName}/${DBName}"}}
                    {:id 188 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "MIRRORLOGPATH" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:MIRRORLOGPATH]}} :verify {:type :eq :rule-fn-extra-paras ["/db/mirlog/${InstName}/${DBName}"] :rule-fn "verify-fn-eq" :rule-description "/db/mirlog/${InstName}/${DBName}"}}
                    {:id 189 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "BLK_LOG_DSK_FUL" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:BLK_LOG_DSK_FUL]}} :verify {:type :eq :rule-fn-extra-paras ["NO"] :rule-fn "verify-fn-eq" :rule-description "NO"}}
                    {:id 190 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "BLOCKNONLOGGED" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:BLOCKNONLOGGED]}} :verify {:type :eq :rule-fn-extra-paras ["YES"] :rule-fn "verify-fn-eq" :rule-description "YES"}}
                    {:id 191 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "MAX_LOG" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:MAX_LOG]}} :verify {:type :eq :rule-fn-extra-paras [30] :rule-fn "verify-fn-eq" :rule-description "30"}}
                    {:id 192 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "NUM_LOG_SPAN" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:NUM_LOG_SPAN]}} :verify {:type :eq :rule-fn-extra-paras [27] :rule-fn "verify-fn-eq" :rule-description "LOGPRIMARY*0.9"}}
                    {:id 193 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "SOFTMAX" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:SOFTMAX]}} :verify {:type :eq :rule-fn-extra-paras [15] :rule-fn "verify-fn-eq" :rule-description "20M / (LOGFILSIZ*4K)*100
（10M / (LOGFILSIZ*4K)*100 <=$<= 50M / (LOGFILSIZ*4K)*100"}}
                    {:id 194 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGARCHMETH1" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGARCHMETH1]}} :verify {:type :eq :rule-fn-extra-paras ["DISK:/db/archm1"] :rule-fn "verify-fn-eq" :rule-description "DISK:/db/archm1"}}
                    {:id 195 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGARCHMETH2" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGARCHMETH2]}} :verify {:type :eq :rule-fn-extra-paras ["DISK:/db/archm2"] :rule-fn "verify-fn-eq" :rule-description "DISK:/db/archm2"}}
                    {:id 196 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTORESTART" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTORESTART]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 197 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "INDEXREC" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:INDEXREC]}} :verify {:type :eq :rule-fn-extra-paras ["SYSTEM|RESTART"] :rule-fn "verify-fn-eq" :rule-description "SYSTEM|RESTART"}}
                    {:id 198 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "LOGINDEXBUILD" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:LOGINDEXBUILD]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON"}}
                    {:id 199 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "NUM_DB_BACKUPS" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:NUM_DB_BACKUPS]}} :verify {:type :eq :rule-fn-extra-paras [12] :rule-fn "verify-fn-eq" :rule-description "12"}}
                    {:id 200 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "REC_HIS_RETENTN" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:REC_HIS_RETENTN]}} :verify {:type :eq :rule-fn-extra-paras [12] :rule-fn "verify-fn-eq" :rule-description "12"}}
                    {:id 201 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_DEL_REC_OBJ" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_DEL_REC_OBJ]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 202 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_MAINT" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_MAINT]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 203 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_DB_BACKUP" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_DB_BACKUP]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 204 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_TBL_MAINT" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_TBL_MAINT]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 205 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_RUNSTATS" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_RUNSTATS]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 206 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_STMT_STATS" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_STMT_STATS]}} :verify {:type :eq :rule-fn-extra-paras [:OFF] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 207 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_STATS_PROF" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_STATS_PROF]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 208 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_PROF_UPD" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_PROF_UPD]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}
                    {:id 209 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :db-parameter :second-cat-label "DB参数" :title "AUTO_REORG" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:AUTO_REORG]}} :verify {:type :eq :rule-fn-extra-paras ["OFF"] :rule-fn "verify-fn-eq" :rule-description "OFF"}}

                    ; [:db-check :first-cat-label "DB检查" :hadr-config]
                    {:id 210 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_HADR_SOSNDBUF" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_HADR_SOSNDBUF]}} :verify {:type :eq :rule-fn-extra-paras [1048576] :rule-fn "verify-fn-eq" :rule-description "1048576"}}
                    {:id 211 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_HADR_SORCVBUF" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_HADR_SORCVBUF]}} :verify {:type :eq :rule-fn-extra-paras [1048576] :rule-fn "verify-fn-eq" :rule-description "1048576"}}
                    {:id 212 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_HADR_NO_IP_CHECK" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_HADR_NO_IP_CHECK]}} :verify {:type :eq :rule-fn-extra-paras ["NO"] :rule-fn "verify-fn-eq" :rule-description "NO【适用于容灾网络使用NAT转换的环境】"}}
                    {:id 213 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_HADR_BUF_SIZE" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_HADR_BUF_SIZE]}} :verify {:type :eq :rule-fn-extra-paras [1024] :rule-fn "verify-fn-eq" :rule-description "Max(Min(LOGBUFSZ)*4，4096)<=$<=( Max(LOGBUFSZ)*4)   >=4096 and <=10240"}}
                    {:id 214 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_HADR_PEER_WAIT_LIMIT" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_HADR_PEER_WAIT_LIMIT]}} :verify {:type :eq :rule-fn-extra-paras [1] :rule-fn "verify-fn-eq" :rule-description "1"}}
                    {:id 215 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_HADR_ROS" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_HADR_ROS]}} :verify {:type :eq :rule-fn-extra-paras ["ON"] :rule-fn "verify-fn-eq" :rule-description "ON （HADR备端只读，按需打开）"}}
                    {:id 216 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "DB2_STANDBY_ISO" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:DB2_STANDBY_ISO]}} :verify {:type :eq :rule-fn-extra-paras ["UR"] :rule-fn "verify-fn-eq" :rule-description "UR （ROS=ON时的建议值）"}}
                    {:id 217 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_DBROLE" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_DBROLE]}} :verify {:type :eq :rule-fn-extra-paras ["NO"] :rule-fn "verify-fn-eq" :rule-description ""}}
                    {:id 218 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_LOCAL_HOST" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_LOCAL_HOST]}} :verify {:type :eq :rule-fn-extra-paras ["hadr1_<sys>"] :rule-fn "verify-fn-eq" :rule-description "hadr1_<sys>【生产】
hadr2_<sys>【容灾"}}
                    {:id 219 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_LOCAL_SVC" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_LOCAL_SVC]}} :verify {:type :eq :rule-fn-extra-paras ["hadr1_<instname>_<DBNAME>"] :rule-fn "verify-fn-eq" :rule-description "hadr1_<instname>_<DBNAME>【生产】
hadr2_<instname>_<DBNAME>【容灾】"}}
                    {:id 220 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_REMOTE_HOST" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_REMOTE_HOST]}} :verify {:type :eq :rule-fn-extra-paras ["hadr2_{sys}"] :rule-fn "verify-fn-eq" :rule-description "hadr2_{sys}【生产端】
hadr1_{sys}【容灾端】"}}
                    {:id 221 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_REMOTE_SVC" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_REMOTE_SVC]}} :verify {:type :eq :rule-fn-extra-paras ["hadr2_<instname>_<DBNAME>"] :rule-fn "verify-fn-eq" :rule-description "hadr2_<instname>_<DBNAME>【生产端】
hadr1_<instname>_<DBNAME>【容灾端】"}}
                    {:id 222 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_REMOTE_INST" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_REMOTE_INST]}} :verify {:type :eq :rule-fn-extra-paras ["<instname>"] :rule-fn "verify-fn-eq" :rule-description "<instname>"}}
                    {:id 223 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_TIMEOUT" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_TIMEOUT]}} :verify {:type :eq :rule-fn-extra-paras [120] :rule-fn "verify-fn-eq" :rule-description "120（30<=$<=120）"}}
                    {:id 224 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_SYNCMODE" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_SYNCMODE]}} :verify {:type :eq :rule-fn-extra-paras ["ASYNC"] :rule-fn "verify-fn-eq" :rule-description "ASYNC【远程容灾】
NEARSYNC【本地容灾】
SUPERASYNC【多点容灾】"}}
                    {:id 225 :type [:cdc :local] :first-cat :db-check :first-cat-label "DB检查" :second-cat :hadr-config :second-cat-label "HADR配置" :title "HADR_PEER_WINDOW" :execute {:script-name "get_aix_dbcfg.py" :input [{:name :machine :command-line "-o"} {:name :instance :command-line "-i"} {:name :version :command-line "-v"}] :output {:field-path [:HADR_PEER_WINDOW]}} :verify {:type :eq :rule-fn-extra-paras [0] :rule-fn "verify-fn-eq" :rule-description "0"}}

                       {:id 226 :type [:cdc :local] :first-cat :manual-check :first-cat-label "手工检查" :second-cat :all-manual-check :second-cat-label "所有手工检查" :title "用户密码" :execute {:script-name "get_aix_network.py" :input [{:name :machine :command-line "-o"}] :output {:field-path [:laytency]}} :verify {:type :eq :rule-fn-extra-paras [0] :rule-fn "verify-fn-eq" :rule-description "0"}}

                       ])


;;; default verification db

(defstate default-verification :start identity)
